CREATE TABLE [dbo].[tbl_Exercise]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] VARCHAR(100) NOT NULL, 
    [Type] SMALLINT NOT NULL,
    [InvolvedMuscles] SMALLINT NOT NULL,
    [fk_UserId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES tbl_User(Id) 

)
