CREATE TABLE [dbo].[tbl_WorkoutPlan]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] VARCHAR(100) NOT NULL, 
    [IsActive] BIT NOT NULL DEFAULT 0, 
    [fk_UserId] NVARCHAR(128) NOT NULL FOREIGN KEY REFERENCES tbl_User(Id), 
    [IsArchived] BIT NOT NULL DEFAULT 0
)
