name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-prod:
    name: Deploy to Production
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore bb-project.app/bb-project.app.sln

      - name: Build
        run: dotnet build bb-project.app/bb-project.app.Server/bb-project.app.Server.csproj --no-restore --configuration Release

      - name: Publish
        run: dotnet publish bb-project.app/bb-project.app.Server/bb-project.app.Server.csproj --no-build --configuration Release --output ./publish

      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bb-project-api'
          slot-name: 'Production'
          package: ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_91706B8420444488A78CAB69A96544E2 }}

  deploy-test:
    name: Deploy to Test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore bb-project.app/bb-project.app.sln

      - name: Build
        run: dotnet build bb-project.app/bb-project.app.Server/bb-project.app.Server.csproj --no-restore --configuration Release

      - name: Publish
        run: dotnet publish bb-project.app/bb-project.app.Server/bb-project.app.Server.csproj --no-build --configuration Release --output ./publish

      - name: Deploy to Azure Web App (Test)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bb-project-api-test'
          slot-name: 'Production'
          package: ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C09AB169D3204D129570A05F2A237266 }}
